spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: O1Route
          uri: lb://O1
          predicates:
            - Path=/O1/**
          filters:
            - RewritePath=/O1/(?<segment>.*), /$\{segment}
            - SetResponseHeader=X-Gateway-Route, O1
        - id: O2Route
          uri: lb://O2
          predicates:
            - Path=/O2/**
          filters:
            - RewritePath=/O2/(?<segment>.*), /$\{segment}
            - SetResponseHeader=X-Gateway-Route, O2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
