server:
  port: 8081
  address: 0.0.0.0 # Open Address For Feign
spring:
  application:
    name: O1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouds?serverTimezone=UTC
    username: 'root'
    password: '000000'

eureka:
  instance:
    lease-renewal-interval-in-seconds: 15
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

resilience4j:
  ratelimiter:
    instances:
      LIMITER_RULE:
        limit-for-period: 50
        limit-refresh-period: 1s
        timeout-duration: 100ms
  circuitbreaker:
    instances:
      BREAKER_RULE:
        failureRateThreshold: 50
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    export:
      prometheus:
        enabled: true
mylog:
  enable: true
  version: 1.0.0
